Accept empty payload when sending push notification (transit-movements-push-notifications)
hmrc/transit-movements-push-notifications pull request #13
Opened 2023-03-20 09:45 UTC by olakunlekuye2

2023-03-20 09:55 UTC, liandra-giacomine commented on app/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationController.scala
> +    println(s"postNotification called with movementId=$movementId, messageId=$messageId")
remove printlns

2023-03-20 09:56 UTC, liandra-giacomine commented on app/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationController.scala
> +            Future.successful(BadRequest("Missing messageId"))
if it's always a bad request if we don't have the messageId then why is it optional? :)

2023-03-20 09:58 UTC, olakunlekuye2 commented on app/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationController.scala
> +            Future.successful(BadRequest("Missing messageId"))
Okay I'll remove that case

2023-03-20 09:58 UTC, liandra-giacomine commented on app/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationController.scala
> +  override lazy val streamFromMemory: BodyParser[Source[ByteString, _]] = BodyParser {
shouldn't this be in the StreamingParser module?

2023-03-20 10:00 UTC, olakunlekuye2 commented on app/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationController.scala
> +  override lazy val streamFromMemory: BodyParser[Source[ByteString, _]] = BodyParser {
Maybe but it was always in the controller , should I move it ?

2023-03-20 10:01 UTC, liandra-giacomine commented on app/uk/gov/hmrc/transitmovementspushnotifications/services/PushPullNotificationService.scala
> +            body.get
If we have the content length then we expect a body but it's possible there won't be one and this would then throw an unhandled exception I think. Probably better to match the option:

```
body match {
case None => pushPullNotificationConnector.postNotification(boxAssociation.boxId, MessageNotification(uri, None))
case Some(body) => contentLength
        .flatMap(_.toIntOption)
         .filter(_ <= appConfig.maxPushPullPayloadSize) etc etc
}
```

2023-03-20 10:01 UTC, liandra-giacomine commented on test/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationControllerSpec.scala
> +//  def convertPushPullNotificationErrorToPresentationError(error: PushPullNotificationError): PresentationError =
remove commented out code

2023-03-20 10:02 UTC, liandra-giacomine requested changes
bit of clean up needed

2023-03-20 10:03 UTC, liandra-giacomine commented on app/uk/gov/hmrc/transitmovementspushnotifications/controllers/PushNotificationController.scala
> +  override lazy val streamFromMemory: BodyParser[Source[ByteString, _]] = BodyParser {
Happy to keep it here, was just wondering what it was overriding?

2023-03-21 14:40 UTC, sonisn1988 approved these changes
LGTM

2023-03-21 15:22 UTC, sonisn1988 approved these changes

2023-03-21 15:33 UTC, merged